import numpy as np



'''
Author: A. J. Hedge
Created: 28/11/2023
Last Modified: 28/11/2023
Usage: import spectral_line_identification as sl_id
Purpose: Provides structured, operable classes for storing, manipulating and extracting spectral line definitions.
'''

# Class Planner
# LineCatalogue:
#       creates, modifies and retrieves held individual line IDs and line series. Generate from Splatalogue astroquery service.
# LineSeries:
#       creates, modifies and retrieves a series of related lines (e.g. same element/molecule with different transitions)
#       line series can be generated by unique definitions or by a functional definition
# Line:
#       the base line ID which is held by LineCatalogue and LineSeries
#       has properties which describe the line parameters (freq/wavelength, element/molecule, transition type, transition numbers, H2-normalised strength)
#       and properties which describe the display formatting (printing, plotting)





